repos:
- repo: https://github.com/pre-commit/mirrors-black
  rev: stable
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-flake8
  rev: stable
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-isort
  rev: stable
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: stable
  hooks:
  - id: pylint
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: stable
  hooks:
  - id: mypy